from datetime import datetime

from app.twitter_learning_journal.models.book import Book


def get_books():
    return legacy_books


def _date(date_str):
    return datetime.strptime(date_str, '%Y-%m-%d')


legacy_books = [
    Book(screen_name='dev3l_',
         title='Cracking the PM Interview',
         classification='agile',
         pages=364,
         start_date=_date('2017-12-16'),
         stop_date=_date('2017-12-30'),
         ),
    Book(screen_name='dev3l_',
         title='How F*cked Up Is Your Management',
         classification='leadership',
         pages=250,
         start_date=_date('2017-11-11'),
         stop_date=_date('2017-12-15'),
         ),
    Book(screen_name='dev3l_',
         title='Clean Coder',
         classification='engineering',
         pages=210,
         start_date=_date('2017-11-15'),
         stop_date=_date('2017-02-15'),
         ),
    Book(screen_name='dev3l_',
         title='Production Ready Microservices',
         classification='engineering',
         pages=153,
         start_date=_date('2017-10-12'),
         stop_date=_date('2017-11-02'),
         ),
    Book(screen_name='dev3l_',
         title='Head First Python',
         classification='engineering',
         pages=494,
         start_date=_date('2017-07-26'),
         stop_date=_date('2017-10-03'),
         ),
    Book(screen_name='dev3l_',
         title='The Startup Way',
         classification='agile',
         pages=400,
         start_date=_date('2017-08-09'),
         stop_date=_date('2018-01-03'),
         ),
    Book(screen_name='dev3l_',
         title='Pragmatic Thinking and Learning',
         classification='agile',
         pages=251,
         start_date=_date('2017-08-17'),
         stop_date=_date('2017-10-08'),
         ),
    Book(screen_name='dev3l_',
         title='The Mythical Man-Month',
         classification='engineering',
         pages=332,
         start_date=_date('2017-07-03'),
         stop_date=_date('2017-08-13'),
         ),
    Book(screen_name='dev3l_',
         title='Clean Code',
         classification='engineering',
         pages=434,
         start_date=_date('2017-06-07'),
         stop_date=_date('2017-08-05'),
         ),
    Book(screen_name='dev3l_',
         title='User Story Mapping',
         classification='agile',
         pages=324,
         start_date=_date('2017-05-14'),
         stop_date=_date('2017-06-03'),
         ),
    Book(screen_name='dev3l_',
         title='Object Thinking',
         classification='engineering',
         pages=334,
         start_date=_date('2017-04-02'),
         stop_date=_date('2017-05-14'),
         ),
    Book(screen_name='dev3l_',
         title='Pragmatic Programmer',
         classification='engineering',
         pages=321,
         start_date=_date('2017-03-02'),
         stop_date=_date('2017-05-14'),
         ),
]
